#essi esimerkkinä laitteen vilp 1 dallasien kuuntelu
input_number:
  vilp1_vesi_in:
    name: "Vesi IN Vilp 1"
    min: -40
    max: 125
    step: 0.01
  vilp1_vesi_out:
    name: "Vesi OUT Vilp 1"
    min: -40
    max: 125
    step: 0.01
  vilp1_kaasu_in:
    name: "Kaasu IN Vilp 1"
    min: -40
    max: 125
    step: 0.01
  vilp1_kaasu_out:
    name: "Kaasu OUT Vilp 1"
    min: -40
    max: 125
    step: 0.01

automation:
  - alias: "Update VILP 1 Dallas Sensors"
    mode: queued
    trigger:
      - platform: event
        event_type: esphome.dallas_raw
    action:
      - choose:
          - conditions: >
              {{ trigger.event.data.address | lower == '0xeb01221127e6d228' }}
            sequence:
              - service: input_number.set_value
                target:
                  entity_id: input_number.vilp1_vesi_in
                data:
                  value: "{{ trigger.event.data.value | float | round(2) }}"

          - conditions: >
              {{ trigger.event.data.address | lower == '0xdb012211072f6b28' }}
            sequence:
              - service: input_number.set_value
                target:
                  entity_id: input_number.vilp1_vesi_out
                data:
                  value: "{{ trigger.event.data.value | float | round(2) }}"

          - conditions: >
              {{ trigger.event.data.address | lower == '0x66012211281e8a28' }}
            sequence:
              - service: input_number.set_value
                target:
                  entity_id: input_number.vilp1_kaasu_in
                data:
                  value: "{{ trigger.event.data.value | float | round(2) }}"

          - conditions: >
              {{ trigger.event.data.address | lower == '0x71012211374bde28' }}
            sequence:
              - service: input_number.set_value
                target:
                  entity_id: input_number.vilp1_kaasu_out
                data:
                  value: "{{ trigger.event.data.value | float | round(2) }}"

template:
  - sensor:
      - name: "Vesi IN Vilp 1"
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        state: "{{ states('input_number.vilp1_vesi_in') | float }}"
      - name: "Vesi OUT Vilp 1"
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        state: "{{ states('input_number.vilp1_vesi_out') | float }}"
      - name: "Kaasu IN Vilp 1"
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        state: "{{ states('input_number.vilp1_kaasu_in') | float }}"
      - name: "Kaasu OUT Vilp 1"
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        state: "{{ states('input_number.vilp1_kaasu_out') | float }}"

