substitutions:
  # Laitteen sijaintitiedot (Koordinaatit pyöristetty tietoturvasyistä)
  device_location: "Hämylä varaajahuone"
  device_lat: "60.0"
  device_lon: "23.0"

esphome:
  name: kellari-onewire-hub-1
  friendly_name: "Kellarin onewire hub 1"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

packages:
  wifi: !include common/wifi.yaml         # wifi pyöristetty packagen kautta (useampi verkko, prio järjestys sekä secrettikäsittelyn kautta)
  otaapi: !include common/otaapi.yaml     # ota ja api pyöristetty packagen kautta (eräissä tiloissa kireähköt säädöt, eräissä löysemmät)

logger:
  level: VERBOSE

time:
  - platform: sntp
    id: sntp_time
    timezone: "EET-2EEST,M3.5.0/3,M10.5.0/4" # Suomi Hesuli alkuvuodesta 2026, ennenkuin lakimuutoksella saadaan pysyvä normaaliaika koko suomeen, tai mahdollisesti EU:n tai koko maailman viralliseksi ajaksi suomen normaaliaika ISO 8601 muodossa, tanskalaisella sorttauksella
    servers:
      # vain julkiset, tietoturvasyistä)
      - ntp.netnod.se

# =============================================================================
# VÄYLÄMÄÄRITYKSET - scan: ALL hävitetty koska hävinnyt koodista
# =============================================================================
one_wire:
  - platform: gpio
    id: ow_bus_1
    pin: GPIO25
  - platform: gpio
    id: ow_bus_2
    pin: GPIO26
  - platform: gpio
    id: ow_bus_3
    pin: GPIO18

# =============================================================================
# SENSORIT (Dallas/1-Wire)
#
# HUOMIO: Koska dallas/one_wire-komponentin tuki automaattiselle skannaukselle
# ja dynaamiselle iteraatiolle on nykyisissä versioissa rajallinen, toteutamme
# sensorit eksplisiittisesti copypastella. 
# Rakkaudesta lajiin ja raakaan YAML-vääntöön.
# =============================================================================

sensor:
  # ===========================================================================
  # BUSSI 1 (GPIO25) - 4 Sensoria
  # ===========================================================================
  - platform: dallas_temp
    one_wire_id: ow_bus_1
    index: 0
    id: b1_i0
    name: "Väylä 1 Anturi 0"
    update_interval: 30s
    filters:
      - filter_out: nan
      - filter_out: 0.0    # Suodatetaan virheelliset nollat
      - filter_out: 85.0   # Dallasin tyypillinen virhearvo (Power-on reset)
      - filter_out: -127.0 # Yhteysvirhe
      # muut havaitut virhetilanteet poistettu tietotorvasyistä
    on_value:
      then:
        - delay: 200ms # Jos cpu on joskus kiireinen, eikä heti kerkiäkään tehdä oikeita töitä
        - if:
            condition:
              lambda: 'return !std::isnan(x);'
            then:
              - homeassistant.event:
                  event: esphome.dallas_raw
                  data:
                    address: !lambda 'return id(b1_i0).get_address_name();'
                    value: !lambda 'return str_sprintf("%.2f", x);'
                    hub: kellari-onewire-hub-1

  # Toistetaan sama rakenne muille antureille... index: korotus +1, id: b1 = ow_bus_1 _i0 korotus +1 name: korotus +1
  # (Konfiguraatio jatkuu vastaavalla tavalla väylille 1-8 (esim. ow_bus_1, ow_bus_2, ow_bus_3...)
