# packages/netatmo_tyohuone.yaml
#
# TYÖHUONEEN VAKAA JA HITAAMPI PID-POHJAINEN LÄMMÖNSÄÄTÖ
# (RuuviTag + Netatmo + UPS-kuormakompensaatio)
#
# Tämä konfiguraatio toteuttaa Home Assistantissa maltillisesti
# viritetyn PID-säätimen Netatmo-termostaatille käyttäen
# RuuviTag-lämpötila-anturia todellisena mittauspisteenä.
#
# Säätö on optimoitu:
# - vähäiseen oskillointiin
# - hitaaseen lämpömassaan (patterilämmitys)
# - Netatmon API:n ja venttiililogiiikan rajoitteisiin
#
# ---------------------------------------------------------------
# SUUNNITTELUFILOSOFIA
# ---------------------------------------------------------------
# Tämä EI pyri aggressiiviseen lämpötilan korjaukseen.
# Tavoitteena on:
# - tasainen lämpö
# - minimaalinen venttiilin sahaus
# - ennakoiva mutta rauhallinen reagointi
#
# Säätö perustuu kaskadiin:
#   PID → virtuaalinen tavoitelämpö
#       → Netatmon sisäinen lämpötila
#       → venttiilin avautuminen
#
# ---------------------------------------------------------------
# KOMPONENTIT
# ---------------------------------------------------------------
#
# 1) PID-SÄÄDIN (P + I + D)
#    - P-Gain: pienempi kuin aiemmassa versiossa → vakaampi käytös
#    - I-Gain: hidas integraali poistamaan pysyvä virhe
#    - D-Gain: vaimentaa äkillisiä muutoksia
#
#    Kaikki parametrit ovat säädettävissä käyttöliittymästä
#    ilman uudelleenkäynnistystä.
#
# 2) INTEGRAALIN ANTI-WINDUP
#    - Integraali ei kasva, jos Netatmon venttiili on jo ääriasennossa
#    - Estää lämpötilan “karkaamisen” ja pitkän palautumisajan
#
# 3) UPS-POHJAINEN DYNAAMINEN KOMPENSAATIO
#    - UPS:n tehonkulutus toimii hukkalämmön indikaattorina
#    - Kuormitus laskee tavoitelämpötilaa lineaarisesti
#    - Suodatettu 5 minuutin liukuvalla keskiarvolla
#
# 4) 10 MINUUTIN OHJAUSSILMUKKA
#    - PID-laskenta ja Netatmo-ohjaus suoritetaan 10 min välein
#    - Sopii patterilämmityksen hitaaseen dynamiikkaan
#
# 5) KASKADIOHJAUS + SLEW RATE -RAJOITUS
#    - Netatmon setpointia muutetaan vain vähän kerrallaan
#    - Muutos per sykli on rajoitettu ±0.3…0.5 °C
#    - Lopullinen arvo kvantisoidaan 0.5 °C askeliin
#
# ---------------------------------------------------------------
# MIKSI TÄMÄ TOIMII NETATMON KANSSA
# ---------------------------------------------------------------
# Netatmo:
# - odottaa hitaita muutoksia
# - ei pidä jatkuvasta sahaamisesta
# - reagoi paremmin pieniin mutta säännöllisiin korjauksiin
#
# Tämä konfiguraatio:
# - "puhuu Netatmon kieltä"
# - antaa sille aikaa reagoida
# - mutta käyttää silti ulkoista, tarkempaa anturia
#
# ---------------------------------------------------------------
# VAATIMUKSET
# ---------------------------------------------------------------
# - climate.tyohuone (Netatmo)
# - RuuviTag lämpötila-anturi
# - UPS-tehosensori (sensor.tyohuone_ups_power_watts)
#
# ---------------------------------------------------------------
# TULOS
# ---------------------------------------------------------------
# Lopputulos on rauhallinen, huomaamaton ja hyvin ennustettava
# lämmönsäätö, joka toimii arjessa ilman jatkuvaa hienosäätöä.
#
# Tämä on tarkoituksella "hidas mutta viisas" säädin.
#
# Käytä, säädä ja riko rauhassa.
#
# packages/tyohuone_v2025-12-18.yaml

input_number:
  tyohuone_target:
    name: "Tyohuone Tavoitelampotila"
    min: 17
    max: 22
    step: 0.1
    unit_of_measurement: "°C"
    initial: 21.0
  
  tyokkari_kerroin_slider:
    name: "Työhuone Kerroin (P-Gain)"
    min: 1
    max: 15
    step: 0.1
    initial: 2.0
  
  tyokkari_i_gain_slider:
    name: "Työhuone I-Gain (Ki)"
    min: 0.00
    max: 0.10
    step: 0.001
    unit_of_measurement: "Ki"
    initial: 0.004

  tyohuone_d_gain_slider:
    name: "Työhuone D-Gain (Kd)"
    min: 0.0
    max: 5.0
    step: 0.1
    initial: 1.0

  tyohuone_target_base:
    name: "Työhuone Base Lämpötila"
    min: 17
    max: 22
    step: 0.1
    unit_of_measurement: "°C"
    initial: 21.0

  tyokkari_integral_accumulator:
    name: "Työhuone I-Muisti"
    min: -1.0
    max: 1.0
    step: 0.0001
    initial: 0.0

  tyohuone_error_storage:
    name: "Työhuone Virhemuisti"
    min: -5.0
    max: 5.0
    step: 0.001
    initial: 0.0

template:
  - sensor:
      - name: "Tyohuone Venttiili Prosentti"
        unit_of_measurement: "%"
        state: "{{ state_attr('climate.tyohuone', 'heating_power_request') | int(0) }}"
        icon: mdi:radiator-variant

  - sensor:
      - name: "Tyohuoneen PI-laskettu Lampotila"
        unique_id: tyohuoneen_pi_laskettu_lampotila
        unit_of_measurement: "°C"
        state: >
          {% set current = states('sensor.ruuvitag_6b98_temperature') | float(21.0) %}
          {% set target = states('input_number.tyohuone_target') | float(21.0) %}
          {% set kp = states('input_number.tyokkari_kerroin_slider') | float(4.0) %}
          {% set kd = states('input_number.tyohuone_d_gain_slider') | float(2.5) %}
          {% set integral = states('input_number.tyokkari_integral_accumulator') | float(0) %}
          {% set last_error = states('input_number.tyohuone_error_storage') | float(0) %}
          
          {% set error = target - current %}
          {% set derivative = error - last_error %}
          
          {% set output = target + (kp * error) + integral + (kd * derivative) %}
          
          {{ ([16.0, output, 24.0] | sort)[1] | round(2) }}

sensor:
  - platform: filter
    name: "Työhuone UPS Teho Keskiarvo"
    entity_id: sensor.tyohuone_ups_power_watts
    filters:
      - filter: time_simple_moving_average
        window_size: "00:05:00"
        precision: 1

automation:

# --- 1. DYNAAMINEN TAVOITE (UPS KOMPENSOINTI) ---
  - alias: "Työhuone: Dynaaminen Setpoint UPS-kuorman mukaan"
    id: tyohuone_dynamic_setpoint_ups
    mode: restart
    trigger:
      - platform: state
        entity_id: sensor.tyohuone_ups_teho_keskiarvo
      - platform: state
        entity_id: input_number.tyohuone_target_base
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.tyohuone_target
        data:
          value: >
            {% set base = states('input_number.tyohuone_target_base') | float(21.0) %}
            {% set power = states('sensor.tyohuone_ups_teho_keskiarvo') | float(0) %}
            {% set compensation = (power / 200) * 0.1 %}
            {{ (base - compensation) | round(2) }}

# --- 2. INTEGRAALIN PÄIVITYS (ANTI-WINDUP) ---
  - alias: "Työhuone PID-Controller - Integral Kumulaatio"
    id: tyohuone_pid_integral_update
    mode: single
    trigger:
      - platform: time_pattern
        minutes: "/10" 
    action:
      - variables:
          ki: "{{ states('input_number.tyokkari_i_gain_slider') | float(0.008) }}"
          current_temp: "{{ states('sensor.ruuvitag_6b98_temperature') | float(21.0) }}"
          target_temp: "{{ states('input_number.tyohuone_target') | float(21.0) }}"
          old_i: "{{ states('input_number.tyokkari_integral_accumulator') | float(0) }}"
          error: "{{ target_temp - current_temp }}"
          valve: "{{ state_attr('climate.tyohuone', 'heating_power_request') | int(0) }}"

      - service: input_number.set_value
        target:
          entity_id: input_number.tyokkari_integral_accumulator
        data:
          value: >
            {# Anti-Windup: Pysäytetään integraali jos venttiili on jo ääriasennossa #}
            {% if (valve >= 100 and error > 0) or (valve <= 0 and error < 0) %}
              {{ old_i }}
            {% else %}
              {% set new_i = old_i + (ki * error * 10) %}
              {{ [[new_i, -1.0] | max, 1.0] | min | round(4) }}
            {% endif %}

      - service: input_number.set_value 
        target:
          entity_id: input_number.tyohuone_last_temp 
        data:
          value: "{{ current_temp }}"

# --- 3. KASKADIOHJAUS (TIUKEMPI SLEW RATE 0.3°C) ---
  - alias: "Netatmo TempControl - Tyohuone (Slew Rate Limited)"
    id: netatmo_temp_control_tyohuone
    mode: single
    trigger:
      - platform: time_pattern
        minutes: "/10" 
    variables:
      pid_output: "{{ states('sensor.tyohuoneen_pi_laskettu_lampotila') | float(21.0) }}"
      current_real: "{{ states('sensor.ruuvitag_6b98_temperature') | float(21.0) }}"
      delta: "{{ pid_output - current_real }}"
      netatmo_internal_temp: "{{ state_attr('climate.tyohuone', 'current_temperature') | float(21.0) }}"
      raw_target: "{{ netatmo_internal_temp + delta }}"
      current_setpoint: "{{ state_attr('climate.tyohuone', 'temperature') | float(21.0) }}"
      
      # MUUTETTU: Tiukempi rajoitin 0.5 -> 0.3 estämään oskillointia
      diff: "{{ raw_target - current_setpoint }}"
      limited_diff: "{{ [[diff, -0.5] | max, 0.5] | min }}"
      
      final_temp: "{{ ((current_setpoint + limited_diff) * 2) | round(0) / 2 }}"
    action:
      - service: climate.set_temperature
        target:
          entity_id: climate.tyohuone
        data:
          temperature: "{{ final_temp }}"
