# packages/netatmo_tyohuone.yaml
#
# TYÖHUONEEN VAKAA JA HITAAMPI PID-POHJAINEN LÄMMÖNSÄÄTÖ
# (RuuviTag + Netatmo + UPS-kuormakompensaatio)
#
# Tämä konfiguraatio toteuttaa Home Assistantissa maltillisesti
# viritetyn PID-säätimen Netatmo-termostaatille käyttäen
# RuuviTag-lämpötila-anturia todellisena mittauspisteenä.
#
# Säätö on optimoitu:
# - vähäiseen oskillointiin
# - hitaaseen lämpömassaan (patterilämmitys)
# - muihin ulkoisiin tekijöihin, nyt talvelle ups:n kuorman mukaan aleneva pyyntö, keväällä ehkä otetaan aurinko mukaan leikkeihin
# - Netatmon API:n ja venttiililogiiikan rajoitteisiin
#
# ---------------------------------------------------------------
# SUUNNITTELUFILOSOFIA
# ---------------------------------------------------------------
# Tämä EI pyri aggressiiviseen lämpötilan korjaukseen.
# Tavoitteena on:
# - tasainen lämpö
# - minimaalinen venttiilin sahaus
# - ennakoiva mutta rauhallinen reagointi
#
# Säätö perustuu kaskadiin:
#   PID → virtuaalinen tavoitelämpö
#       → Netatmon sisäinen lämpötila
#       → venttiilin avautuminen
#
# ---------------------------------------------------------------
# KOMPONENTIT
# ---------------------------------------------------------------
#
# 1) PID-SÄÄDIN (P + I + D)
#    - P-Gain: pienempi kuin aiemmassa versiossa → vakaampi käytös
#    - I-Gain: hidas integraali poistamaan pysyvä virhe
#    - D-Gain: vaimentaa äkillisiä muutoksia
#
#    Kaikki parametrit ovat säädettävissä käyttöliittymästä
#    ilman uudelleenkäynnistystä.
#
# 2) INTEGRAALIN ANTI-WINDUP
#    - Integraali ei kasva, jos Netatmon venttiili on jo ääriasennossa
#    - Estää lämpötilan “karkaamisen” ja pitkän palautumisajan
#
# 3) UPS-POHJAINEN DYNAAMINEN KOMPENSAATIO
#    - UPS:n tehonkulutus toimii hukkalämmön indikaattorina
#    - Kuormitus laskee tavoitelämpötilaa lineaarisesti
#    - Suodatettu 5 minuutin liukuvalla keskiarvolla
#
# 4) 10 MINUUTIN OHJAUSSILMUKKA
#    - PID-laskenta ja Netatmo-ohjaus suoritetaan 10 min välein
#    - Sopii patterilämmityksen hitaaseen dynamiikkaan
#
# 5) KASKADIOHJAUS + SLEW RATE -RAJOITUS
#    - Netatmon setpointia muutetaan vain vähän kerrallaan
#    - Lopullinen arvo kvantisoidaan 0.5 °C askeliin
#
# ---------------------------------------------------------------
# MIKSI TÄMÄ TOIMII NETATMON KANSSA
# ---------------------------------------------------------------
# Netatmo:
# - odottaa hitaita muutoksia
# - ei pidä jatkuvasta sahaamisesta
# - reagoi paremmin pieniin mutta säännöllisiin korjauksiin
#
# Tämä konfiguraatio:
# - "puhuu Netatmon kieltä"
# - antaa sille aikaa reagoida
# - mutta käyttää silti ulkoista, tarkempaa anturia
#
# ---------------------------------------------------------------
# VAATIMUKSET
# ---------------------------------------------------------------
# - climate.tyohuone (Netatmo)
# - RuuviTag lämpötila-anturi
# - Tehosensori, esim. shelly tai ups (sensor.tyohuone_ups_power_watts)
#
# ---------------------------------------------------------------
# TULOS
# ---------------------------------------------------------------
# Lopputulos on rauhallinen, huomaamaton ja hyvin ennustettava
# lämmönsäätö, joka toimii arjessa ilman jatkuvaa hienosäätöä.
#
# Tämä on tarkoituksella "hidas mutta viisas" säädin.
#
# Käytä, säädä ja riko rauhassa.
#
# packages/tyohuone_v2025-12-21.yaml
input_number:
  tyohuone_target:
    name: "Työhuone Tavoitelämpötila"
    min: 17
    max: 22
    step: 0.1
    unit_of_measurement: "°C"
    initial: 20.0

  tyohuone_target_base:
    name: "Työhuone Base Lämpötila"
    min: 17
    max: 22
    step: 0.1
    unit_of_measurement: "°C"
    initial: 21.0

  tyokkari_kerroin_slider:
    name: "Työhuone Kerroin (Kp)"
    min: 1
    max: 15
    step: 0.1
    initial: 4.0

  tyokkari_i_gain_slider:
    name: "Työhuone I-Gain (Ki)"
    min: 0.00
    max: 0.10
    step: 0.001
    unit_of_measurement: "Ki"
    initial: 0.008

  tyohuone_d_gain_slider:
    name: "Työhuone D-Gain (Kd)"
    min: 0.0
    max: 10.0
    step: 0.1
    initial: 2.5

  tyokkari_integral_accumulator:
    name: "Työhuone I-Muisti"
    min: -2.5
    max: 2.5
    step: 0.0001
    initial: 0.0

  tyohuone_last_temp:
    name: "Työhuone Viime Lämpötila"
    min: 0.0
    max: 35.0
    step: 0.01
    initial: 21.0

template:
  - sensor:
      - name: "Tyohuone Venttiili Prosentti"
        unit_of_measurement: "%"
        state: "{{ state_attr('climate.tyohuone', 'heating_power_request') | int(0) }}"
        icon: mdi:radiator-variant

      - name: "Tyohuone PID Ohjausarvo"
        unit_of_measurement: "°C"
        state: "{{ state_attr('climate.tyohuone', 'temperature') }}"
        icon: mdi:thermometer-lines

sensor:
  - platform: filter
    name: "Työhuone UPS Teho Keskiarvo"
    entity_id: sensor.tyohuone_ups_power_watts
    filters:
      - filter: time_simple_moving_average
        window_size: "00:05:00"
        precision: 1

automation:
  # 1. UPS-KOMPENSAATIO (Laskee tavoitetta kun UPS kuormittuu)
  - alias: "Työhuone: UPS Kompensointi"
    id: tyohuone_ups_comp
    trigger:
      - platform: state
        entity_id: sensor.tyohuone_ups_teho_keskiarvo
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.tyohuone_target
        data:
          value: >
            {% set base = states('input_number.tyohuone_target_base') | float(21.0) %}
            {% set power = states('sensor.tyohuone_ups_teho_keskiarvo') | float(0) %}
            {% if power < 200 %}
              {{ base }}
            {% else %}
              {{ (base - (power / 100) * 0.1) | round(2) }}
            {% endif %}

  # 2. PID-LASKENTA JA KASKADIOHJAUS (10 min sykli)
  - alias: "Työhuone PID Controller Core"
    id: tyohuone_pid_core
    mode: single
    trigger:
      - platform: time_pattern
        minutes: "/10"
    action:
      - variables:
          target: "{{ states('input_number.tyohuone_target') | float }}"
          current: "{{ states('sensor.ruuvitag_6b98_temperature') | float }}"
          last_temp: "{{ states('input_number.tyohuone_last_temp') | float }}"
          kp: "{{ states('input_number.tyokkari_kerroin_slider') | float }}"
          ki: "{{ states('input_number.tyokkari_i_gain_slider') | float }}"
          kd: "{{ states('input_number.tyohuone_d_gain_slider') | float }}"
          old_i: "{{ states('input_number.tyokkari_integral_accumulator') | float }}"
          valve: "{{ state_attr('climate.tyohuone', 'heating_power_request') | int(0) }}"

          # PID Lasku
          error: "{{ target - current }}"
          p_term: "{{ error * kp }}"
          
          # Asymmetrinen integraali (2x nopeampi jarrutus ylilämmölle)
          effective_ki: "{% if error < 0 %}{{ ki * 2.0 }}{% else %}{{ ki }}{% endif %}"
          new_i: >
            {% if (valve >= 100 and error > 0) or (valve <= 0 and error < 0) %}
              {{ old_i }}
            {% else %}
              {% set calc_i = old_i + (effective_ki * error * 10) %}
              {{ [[calc_i, -2.5] | max, 2.5] | min | round(4) }}
            {% endif %}

          d_term: "{{ kd * (last_temp - current) }}"
          pid_output: "{{ current + p_term + new_i + d_term }}"

      # Päivitetään muuttujat
      - service: input_number.set_value
        target:
          entity_id: input_number.tyokkari_integral_accumulator
        data:
          value: "{{ new_i }}"

      - service: input_number.set_value
        target:
          entity_id: input_number.tyohuone_last_temp
        data:
          value: "{{ current }}"

      # Kaskadiohjaus + Slew Rate (0.5°C)
      - variables:
          netatmo_internal: "{{ state_attr('climate.tyohuone', 'current_temperature') | float(current) }}"
          current_setpoint: "{{ state_attr('climate.tyohuone', 'temperature') | float(current) }}"
          delta: "{{ pid_output - current }}"
          raw_target: "{{ netatmo_internal + delta }}"
          limited_diff: "{{ [[(raw_target - current_setpoint), -0.5] | max, 0.5] | min }}"
          final_temp: "{{ (([10.0, ((current_setpoint + limited_diff) * 2 | round(0) / 2), 25.0] | sort)[1]) | round(1) }}"

      - service: climate.set_temperature
        target:
          entity_id: climate.tyohuone
        data:
          temperature: "{{ final_temp }}"
