# packages/netatmo_tyohuone.yaml
#
# TYÖHUONEEN EDISTYNYT LÄMMÖNSÄÄTÖ (PID + KASKADI + UPS-KOMPENSAATIO)
#
# Tämä paketti toteuttaa Home Assistantissa Netatmo-termostaatille
# ulkoisen, ohjelmallisen PID-säätimen käyttäen RuuviTag-lämpötila-anturia.
#
# Kokonaisuus ohittaa Netatmon sisäisen "mustan laatikon" logiikan
# ja käyttää Netatmoa vain venttiilin ohjausrajapintana.
#
# ---------------------------------------------------------------
# PÄÄPERIAATE
# ---------------------------------------------------------------
# - RuuviTag mittaa todellisen huonelämpötilan
# - Home Assistant laskee PID-säätimen avulla "virtuaalisen tavoitelämpötilan"
# - Netatmolle EI anneta suoraan absoluuttista tavoitetta
#   vaan sitä ohjataan kaskadina sen oman sisäisen lämpötilan kautta
#
# → Lopputulos: rauhallinen, ennakoiva ja hyvin säädettävä lämmönhallinta
#
# ---------------------------------------------------------------
# SISÄLTÖ
# ---------------------------------------------------------------
#
# 1) PID-SÄÄDIN (P + I + D)
#    - P (proportionaalinen): nopea reagointi virheeseen
#    - I (integraali): poistaa pysyvän virheen (anti-windup mukana)
#    - D (derivaatta): vaimentaa ylilyöntejä
#
#    Kaikki gainit ovat säädettävissä UI-slidereilla lennossa.
#
# 2) 10 MINUUTIN PAKKOSYKLI
#    - Netatmo ei aina reagoi, jos setpoint ei muutu
#    - Tässä ohjaus ajetaan väkisin 10 minuutin välein
#    - Myös "sama arvo uudelleen" lähetetään Netatmolle
#
# 3) KASKADIOHJAUS
#    - PID laskee ideaalisen lämpötilan RuuviTagin perusteella
#    - Muutos muunnetaan Netatmon sisäiseen asteikkoon
#    - Yhden syklin muutos on rajoitettu ±0.5 °C
#    - Lopullinen setpoint kvantisoidaan 0.5 °C askeliin
#
# 4) UPS-KUORMAPOHJAINEN DYNAAMINEN KOMPENSAATIO
#    - UPS:n tehonkulutus indikoi työhuoneen hukkalämpöä
#    - >200 W kuorma alkaa laskea tavoitelämpötilaa
#    - Skaala: -0.1 °C / 100 W
#    - Suodatettu 5 min liukuvalla keskiarvolla
#
# 5) NETATMO-FEEDBACK
#    - Luetaan Netatmon:
#        * sisäinen lämpötila
#        * venttiilin aukioloprosentti (heating_power_request)
#    - Käytetään anti-windup-logiikassa ja diagnostiikassa
#
# ---------------------------------------------------------------
# MIKSI TÄMÄ ON TARPEEN?
# ---------------------------------------------------------------
# Netatmon oma säätö:
# - reagoi hitaasti
# - käyttää väärää mittauspistettä (termostaatin sijainti)
# - ei huomioi huoneen todellista lämpökuormaa
#
# Tämä ratkaisu:
# - mittaa lämpötilan oikeasta paikasta
# - reagoi ennakoivasti
# - on täysin läpinäkyvä ja säädettävä
# - toimii vakaasti myös kuormituksen muuttuessa
#
# ---------------------------------------------------------------
# VAATIMUKSET
# ---------------------------------------------------------------
# - Home Assistant
# - Netatmo climate entity (climate.tyohuone)
# - RuuviTag lämpötila-anturi
# - UPS-tehosensori (sensor.tyohuone_ups_power_watts)
#
# ---------------------------------------------------------------
# HUOMIO
# ---------------------------------------------------------------
# Tämä EI ole "PID teoriassa" -konfiguraatio,
# vaan käytännössä viritetty, Netatmoa kunnioittava
# kaskadisäädin todelliseen asumiseen.
#
# Käytä, säädä ja riko rauhassa.
#

input_number:
  tyohuone_target:
    name: "Tyohuone Tavoitelampotila"
    min: 17
    max: 22
    step: 0.1
    unit_of_measurement: "°C"
    initial: 21.0
  
  tyokkari_kerroin_slider:
    name: "Työhuone Kerroin (P-Gain)"
    min: 1
    max: 15
    step: 0.5
    initial: 4.0
  
  tyokkari_i_gain_slider:
    name: "Työhuone I-Gain (Ki)"
    min: 0.00
    max: 0.10
    step: 0.001
    unit_of_measurement: "Ki"
    initial: 0.008

  tyohuone_d_gain_slider:
    name: "Työhuone D-Gain (Kd)"
    min: 0.0
    max: 5.0
    step: 0.1
    initial: 2.5

  tyohuone_target_base:
    name: "Työhuone Base Lämpötila"
    min: 17
    max: 22
    step: 0.1
    unit_of_measurement: "°C"
    initial: 21.0

  tyokkari_integral_accumulator:
    name: "Työhuone I-Muisti"
    min: -1.0
    max: 1.0
    step: 0.0001
    initial: 0.0

  tyohuone_error_storage:
    name: "Työhuone Virhemuisti"
    min: -5.0
    max: 5.0
    step: 0.001
    initial: 0.0

template:
  - sensor:
      - name: "Tyohuone Venttiili Prosentti"
        unit_of_measurement: "%"
        state: "{{ state_attr('climate.tyohuone', 'heating_power_request') | int(0) }}"
        icon: mdi:radiator-variant
  - sensor:
      - name: "Tyohuoneen PI-laskettu Lampotila"
        unique_id: tyohuoneen_pi_laskettu_lampotila
        unit_of_measurement: "°C"
        state: >
          {% set current = states('sensor.ruuvitag_6b98_temperature') | float(21.0) %}
          {% set target = states('input_number.tyohuone_target') | float(21.0) %}
          {% set kp = states('input_number.tyokkari_kerroin_slider') | float(4.0) %}
          {% set kd = states('input_number.tyohuone_d_gain_slider') | float(2.5) %}
          {% set integral = states('input_number.tyokkari_integral_accumulator') | float(0) %}
          {% set last_error = states('input_number.tyohuone_error_storage') | float(0) %}
          
          {% set error = target - current %}
          {% set derivative = error - last_error %}
          
          {% set output = target + (kp * error) + integral + (kd * derivative) %}
          
          {{ ([16.0, output, 24.0] | sort)[1] | round(2) }}

sensor:
  - platform: filter
    name: "Työhuone UPS Teho Keskiarvo"
    entity_id: sensor.tyohuone_ups_power_watts
    filters:
      - filter: time_simple_moving_average
        window_size: "00:05:00"
        precision: 1

automation:

# --- 1. DYNAAMINEN TAVOITE (UUSI UPS-LOGIIKKA: >200W -> 0.1C/100W) ---
  - alias: "Työhuone: Dynaaminen Setpoint UPS-kuorman mukaan"
    id: tyohuone_dynamic_setpoint_ups
    mode: restart
    trigger:
      - platform: state
        entity_id: sensor.tyohuone_ups_teho_keskiarvo
      - platform: state
        entity_id: input_number.tyohuone_target_base
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.tyohuone_target
        data:
          value: >
            {% set base = states('input_number.tyohuone_target_base') | float(21.0) %}
            {% set power = states('sensor.tyohuone_ups_teho_keskiarvo') | float(0) %}
            {% if power < 200 %}
              {{ base }}
            {% else %}
              {% set compensation = (power / 100) * 0.1 %}
              {{ (base - compensation) | round(2) }}
            {% endif %}

# --- 2. INTEGRAALIN PÄIVITYS (ANTI-WINDUP) ---
  - alias: "Työhuone PID - Integral & Error Update"
    id: tyohuone_pid_integral_update
    mode: single
    trigger:
      - platform: time_pattern
        minutes: "/10"
    action:
      - variables:
          ki: "{{ states('input_number.tyokkari_i_gain_slider') | float(0.008) }}"
          current_temp: "{{ states('sensor.ruuvitag_6b98_temperature') | float(21.0) }}"
          target_temp: "{{ states('input_number.tyohuone_target') | float(21.0) }}"
          last_i: "{{ states('input_number.tyokkari_integral_accumulator') | float(0) }}"
          valve: "{{ state_attr('climate.tyohuone', 'heating_power_request') | int(0) }}"
          error: "{{ target_temp - current_temp }}"
          
      - service: input_number.set_value
        target:
          entity_id: input_number.tyohuone_error_storage
        data:
          value: "{{ error | round(3) }}"

      - service: input_number.set_value
        target:
          entity_id: input_number.tyokkari_integral_accumulator
        data:
          value: >
            {% if (valve >= 100 and error > 0) or (valve <= 0 and error < 0) %}
              {{ last_i }}
            {% else %}
              {% set new_i = last_i + (ki * error * 10) %}
              {{ ([ -1.0, new_i, 1.0 ] | sort)[1] | round(4) }}
            {% endif %}

# --- 3. KASKADIOHJAUS (PAKOTETTU 10 MIN VÄLEIN) ---
  - alias: "Netatmo TempControl - Tyohuone (Pakotettu sykli)"
    id: netatmo_temp_control_tyohuone
    mode: single
    trigger:
      - platform: time_pattern
        minutes: "/10"
    variables:
      pid_output: "{{ states('sensor.tyohuoneen_pi_laskettu_lampotila') | float(21.0) }}"
      current_real: "{{ states('sensor.ruuvitag_6b98_temperature') | float(21.0) }}"
      netatmo_internal_temp: "{{ state_attr('climate.tyohuone', 'current_temperature') | float(21.0) }}"
      delta: "{{ pid_output - current_real }}"
      raw_target: "{{ netatmo_internal_temp + delta }}"
      current_setpoint: "{{ state_attr('climate.tyohuone', 'temperature') | float(21.0) }}"
      diff: "{{ raw_target - current_setpoint }}"
      limited_diff: "{{ [[diff, -0.5] | max, 0.5] | min }}"
      final_temp: "{{ ((current_setpoint + limited_diff) * 2) | round(0) / 2 }}"
    action:
      # Poistettu "IF" ehto, jotta pyyntö menee läpi joka kerta (myös vaikka arvo pysyisi samana)
      - service: climate.set_temperature
        target:
          entity_id: climate.tyohuone
        data:
          temperature: "{{ final_temp }}"
