
        
sensor:
  - platform: history_stats
    name: "Oljypolttimen tuntilaskuri"
    entity_id: binary_sensor.oljypoltin_arvonta_derivoimalla
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
    end: "{{ now() }}"
    
  - platform: template
    sensors:
      oil_burner_consumption:
        friendly_name: "Oljypolttimen litrat"
        value_template: "{{ states('sensor.oljypolttimen_tuntilaskuri') | float * 4.6 }}"
        unit_of_measurement: "liters"
        

  - platform: template
    sensors:
      oil_tank_level_cm:
        friendly_name: "Oil Tank Level"
        unit_of_measurement: "cm"
        value_template: "{{ 102 - (states('sensor.oil_burner_consumption') | float / 37.5) }}"
        
  - platform: template
    sensors:
      oil_consumption_cost:
        friendly_name: "Oil Consumption Cost"
        unit_of_measurement: "€"
        value_template: "{{ (states('sensor.oil_burner_consumption') | float) * 1.288 }}"



automation:
  - alias: "Paivita Oljypolttimen litrat"
    trigger:
      platform: state
      entity_id: binary_sensor.oljypoltin_arvonta_derivoimalla
    action:
      - service: homeassistant.update_entity
        entity_id: sensor.oil_burner_consumption
  - alias: "Paivita Oljysailion cm"
    trigger:
      platform: state
      entity_id: binary_sensor.oljypoltin_arvonta_derivoimalla
    action:
      - service: homeassistant.update_entity
        entity_id: sensor.oil_tank_level_cm
  - alias: "Paivita Oljyn Eurot"
    trigger:
      platform: state
      entity_id: binary_sensor.oljypoltin_arvonta_derivoimalla
    action:
      - service: homeassistant.update_entity
        entity_id: sensor.oil_consumption_cost


